### PR TITLE
Exposes views on the HDBSCAN cluster exemplars

### LINKED ISSUE #217: HDBscan clusterExemplars getter
**Is your feature request related to a problem? Please describe.**
When implementing the HDBScan clustering algorithm, there's no way to know the clusters' centroids that the model has generated through its scanning of my dataset. This feature is already been added to the K-Means algorithm, and it would be really useful to also have it in your DB-Scan implementation.

**Describe the solution you'd like**
The `HdbscanModel` class already has a private attribute `clustersExemplars`, which I suppose contain the clusters' centroids. I think just exposing this attribute through a getter method would solve my issue.

Also, it would be nice to get some function to calculate the distance from one of the clusters' centroid to each point contained in said cluster.

### PR DESCRIPTION
**Pull request by Craigacp**
### Description
Adds a get method for cluster exemplars in HDBSCAN which returns copies of the exemplars (as the vector is mutable), along with a method that returns the exemplar in terms of feature names.

### Motivation
Fixes #217.

### CODE REVIEW

**Comment by Craigacp** [comment]
@geoffreydstewart would you mind looking over this?

**Review by geoffreydstewart — COMMENTED** [review]
These changes look good. I'm not sure if it's worth adding some minimal test coverage for the new `getClusters` method. The logic looks quite safe, but it could be instructive for the community. Additionally, there is an existing test `deserializeHdbscanModelV42Test` where we might consider asserting that calling the `getMaxDistToEdge` method on a `ClusterExemplar` from a v4.2 model returns `Double.NEGATIVE_INFINITY`.

**Comment by Craigacp** [comment]
> These changes look good. I'm not sure if it's worth adding some minimal test coverage for the new `getClusters` method. The logic looks quite safe, but it could be instructive for the community. Additionally, there is an existing test `deserializeHdbscanModelV42Test` where we might consider asserting that calling the `getMaxDistToEdge` method on a `ClusterExemplar` from a v4.2 model returns `Double.NEGATIVE_INFINITY`.

I've expanded the tests to cover those points.

**Review by JackSullivan — APPROVED** [review]
Looks good to me

**Pull request merged**
